apiVersion: apps/v1
kind: Deployment
metadata:
  name: p3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p3
  template:
    metadata:
      labels:
        app: p3
    spec:
      containers:
      - name: p3
        image: lobbyra/miniweb:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: APPNAME
          value: "p3"
---
apiVersion: v1
kind: Service
metadata:
  name: p3
spec: 
  selector:
    app: p3
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: p3
            port:
              number: 80